#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Console IronFlow
 * 
 * Ce fichier sert de point d'entrée pour les commandes en ligne de commande
 * et met à disposition les utilitaires pour interagir avec le framework.
 * 
 * @author IronFlow Team
 * @version 1.0.0
 */

// Définition du chemin de base
define('BASE_PATH', __DIR__);

// Chargement de l'autoloader
require __DIR__ . '/vendor/autoload.php';

// Chargement des variables d'environnement
if (file_exists(__DIR__ . '/.env')) {
   $dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
   $dotenv->safeLoad();
}

// Création et exécution de la console
$kernel = new IronFlow\Console\Kernel('IronFlow Console', '1.0.0');

// Commande ServeCommand pré-enregistrée dans le Kernel
// $kernel->addCommand(new IronFlow\Console\Commands\ServeCommand());

// Exécution de la console
$kernel->run();
