#!/usr/bin/env php
<?php


use IronFlow\Console\Kernel;
use IronFlow\Console\Commands\SetupCommand;
use IronFlow\Console\Commands\Generator\CraftPanelInstallCommand;
use IronFlow\Console\Commands\Generator\MakeAdminCommand;
use IronFlow\Console\Commands\ServeCommand;
use IronFlow\Console\Commands\Generator\MakeModelCommand;
use IronFlow\Console\Commands\Generator\MakeMigrationCommand;
use IronFlow\Console\Commands\Generator\MakeSeederCommand;
use IronFlow\Console\Commands\Generator\MakeFactoryCommand;
use IronFlow\Console\Commands\Generator\MakeFormCommand;
use IronFlow\Console\Commands\Generator\MakeComponentCommand;
use IronFlow\Console\Commands\Generator\MakeValidatorCommand;
use IronFlow\Console\Commands\Generator\MakeServiceCommand;
use IronFlow\Console\Commands\Generator\MakeTestCommand;
use IronFlow\Console\Commands\Generator\RegisterModelCommand;
use IronFlow\Console\Commands\Generator\ScaffoldCommand;


require __DIR__ . '/vendor/autoload.php';

$app = new Kernel();

// Enregistrer les commandes
$app->add(new SetupCommand());
$app->add(new ServeCommand());
$app->add(new MakeModelCommand());
$app->add(new MakeMigrationCommand());
$app->add(new MakeSeederCommand());
$app->add(new MakeFactoryCommand());
$app->add(new MakeFormCommand());
$app->add(new MakeComponentCommand());
$app->add(new MakeValidatorCommand());
$app->add(new MakeServiceCommand());
$app->add(new MakeTestCommand());
$app->add(new ScaffoldCommand());
$app->add(new CraftPanelInstallCommand());
$app->add(new MakeAdminCommand());
$app->add(new RegisterModelCommand());

$app->run();
