#!/usr/bin/env php
<?php

use IronFlow\Console\Commands\ServeCommand;
use IronFlow\Console\Commands\MakeModelCommand;
use IronFlow\Console\Commands\MakeMigrationCommand;
use IronFlow\Console\Commands\MakeSeederCommand;
use IronFlow\Console\Commands\MakeFactoryCommand;
use IronFlow\Console\Commands\MakeFormCommand;
use IronFlow\Console\Commands\MakeComponentCommand;
use IronFlow\Console\Commands\MakeValidatorCommand;
use IronFlow\Console\Commands\MakeServiceCommand;
use IronFlow\Console\Commands\MakeTestCommand;
use IronFlow\Console\Commands\ScaffoldCommand;
use IronFlow\Console\Commands\InstallCommand;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$app = new Application('IronFlow', '1.0.0');

// Enregistrer les commandes
$app->add(new ServeCommand());
$app->add(new MakeModelCommand());
$app->add(new MakeMigrationCommand());
$app->add(new MakeSeederCommand());
$app->add(new MakeFactoryCommand());
$app->add(new MakeFormCommand());
$app->add(new MakeComponentCommand());
$app->add(new MakeValidatorCommand());
$app->add(new MakeServiceCommand());
$app->add(new MakeTestCommand());
$app->add(new ScaffoldCommand());
$app->add(new InstallCommand());

$app->run();
